### ISSUE TITLE
Test suite hangs

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/oneAPI.jl#101]
As reported by @troels:

> When running on Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)
> The test suite stalls when llvm-optimization in level zero are enabled.
>
> Disabling level zero optimizations solves the problem.

https://github.com/JuliaGPU/oneAPI.jl/pull/100

Should be fixed by https://github.com/intel/intel-graphics-compiler/commit/e785722a1ab5d675d7ad62a9ce606f8b0f764a99

**Comment by troels** [comment]
Just a small update on this.

I found that the test suite hangs on a few tests doing multiplication and division between a matrix and a scalar value, when boundschecking is active (like when running the test-suite) and optimizations are active.

The symptom is that the Intel Graphics Compiler enters an infinite loop when trying to do codesinking. I'll send the failing Spirv code to the intel graphics compiler team sometimes later.

**Comment by troels** [comment]
Ok, this bug ought to be fixed by https://github.com/intel/intel-graphics-compiler/pull/199 once (or if) it gets merged.

**Comment by maleadt** [comment]
Nice! I'll ping our contact at Intel to make sure this gets reviewed/merged, and bump the Yggdrasil recipes after that. We can use this issue to track progress on that.

**Comment by maleadt** [comment]
This should be fixed.
