### ISSUE TITLE
ERROR: /tmp/jl_p05O0j-download.gz Can not open the file as archive

### ISSUE THREAD

**Issue by SlausB** [JuliaGPU/oneAPI.jl#137]
`add oneAPI` caused error:

> ERROR: /tmp/jl_p05O0j-download.gz
> Can not open the file as archive

so running tests now ends with:

> ERROR: LoadError: InitError: could not load symbol "LLVMExtraInitializeAllTargets":
> /home/slaus/julia-1.7.1/bin/julia: undefined symbol: LLVMExtraInitializeAllTargets
> Stacktrace:
>   [1] LLVMInitializeAllTargets
>     @ ~/.julia/packages/LLVM/srSVa/lib/libLLVM_extra.jl:10 [inlined]
>   [2] InitializeAllTargets
>     @ ~/.julia/packages/LLVM/srSVa/src/init.jl:58 [inlined]
>   [3] __init__()
>     @ GPUCompiler ~/.julia/packages/GPUCompiler/XwWPj/src/GPUCompiler.jl:50
>   [4] _include_from_serialized(path::String, depmods::Vector{Any})
>     @ Base ./loading.jl:768
>   [5] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
>     @ Base ./loading.jl:854
>   [6] _require(pkg::Base.PkgId)
>     @ Base ./loading.jl:1097
>   [7] require(uuidkey::Base.PkgId)
>     @ Base ./loading.jl:1013
>   [8] require(into::Module, mod::Symbol)
>     @ Base ./loading.jl:997
>   [9] include
>     @ ./Base.jl:418 [inlined]
>  [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
>     @ Base ./loading.jl:1318
>  [11] top-level scope
>     @ none:1
>  [12] eval
>     @ ./boot.jl:373 [inlined]
>  [13] eval(x::Expr)
>     @ Base.MainInclude ./client.jl:453
>  [14] top-level scope
>     @ none:1
> during initialization of module GPUCompiler
> in expression starting at /home/slaus/.julia/packages/oneAPI/zydrg/src/oneAPI.jl:1

What could be the reason?
I have `Ubuntu 20.04; Julia version 1.7.1; OpenCL 2.0`
Thanks in advance.

**Comment by maleadt** [comment]
Make sure you're using the latest version of all packages. Try oneAPI.jl from master.

**Comment by SlausB** [comment]
`] add oneAPI#master` solved the issue! Thank you!
