### ISSUE TITLE
possible miscompilation on Tiger Lake Xe

### ISSUE THREAD

**Issue by leesongun** [JuliaGPU/oneAPI.jl#167]
version : `oneAPI v0.2.2` (edit: reproduced with `master`)
code:
```julia
using oneAPI
arr = oneArray(ones(UInt64, 260));
print(arr .!= 0)
```
result: 
`Bool[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]`
The result is wrong on index 29, 49, 69, 89, 109, 129, 149, 169, 189, 209, 229, 249.
Same thing happens on exact same index for similar code, such as 
```julia
arr = oneArray(zeros(UInt64, 260));
print(arr .== 0)
```
or
```julia
arr = oneArray{UInt64}(1:260);
print(arr .!= 0)
```
this does not happen when `260` is changed to a smaller number.

**Comment by maleadt** [comment]
Dup of https://github.com/JuliaGPU/oneAPI.jl/issues/154?

**Comment by leesongun** [comment]
fixed with current `master`
