### ISSUE TITLE
oneMKL: copy broken

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/oneAPI.jl#243]
As noted in https://github.com/JuliaGPU/oneAPI.jl/pull/242#issuecomment-1307390184; reproduces quickly by executing the oneMKL tests multiple times:

```
❯ jl --project -L test/setup.jl

copy: Test Failed at /home/tim/Julia/pkg/oneAPI/test/onemkl.jl:15
  Expression: Array(A) == Array(B)
   Evaluated: ComplexF32[0.62028897f0 + 0.5680954f0im, 0.8470302f0 + 0.72753716f0im, 0.48795187f0 + 0.21962279f0im, 0.9410701f0 + 0.19438893f0im, 0.03132671f0 + 0.24299073f0im, 0.9167444f0 + 0.53888947f0im, 0.9014001f0 + 0.9751158f0im, 0.8477041f0 + 0.5251923f0im, 0.014673173f0 + 0.01942259f0im, 0.7496979f0 + 0.8727344f0im, 0.30134517f0 + 0.07368064f0im, 0.42843723f0 + 0.2052998f0im, 0.08305049f0 + 0.31514007f0im, 0.55817646f0 + 0.24732232f0im, 0.99573386f0 + 0.2845214f0im, 0.4044994f0 + 0.38024253f0im, 0.90844953f0 + 0.33899027f0im, 0.8413433f0 + 0.40553868f0im, 0.93793666f0 + 0.4310677f0im, 0.064192474f0 + 0.19298851f0im] == ComplexF32[0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im, 0.0f0 + 0.0f0im]
```

@Sarbojit2019  could you take a look?

**Comment by Sarbojit2019** [comment]
@maleadt, Sure! let me take a look.

**Comment by maleadt** [comment]
Thanks!

**Comment by Sarbojit2019** [comment]
@maleadt, It would be great if you can help me know below list of questions

1. What is the life time of an oneArray? I mean when will memory gets destroyed? I think it managed by Julia runtime but is there anyway if user can destroy it? It will be helpful for low resource systems. I am not able to run all tests more than 60 iterations. Level zero throws error saying out of memory
`iamax/iamin: Error During Test at /mnt/c/Users/sarbojit/source/oneAPI.jl/test/onemkl.jl:38
  Got exception outside of a @test
  ZeError: insufficient device memory to satisfy call (code 1879048195, ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY)
  Stacktrace:
    [1] throw_api_error(res::oneAPI.oneL0._ze_result_t)
      @ oneAPI.oneL0 /mnt/c/Users/sarbojit/source/oneAPI.jl/lib/level-zero/error.jl:102
    [2] macro expansion
      @ /mnt/c/Users/sarbojit/source/oneAPI.jl/lib/level-zero/oneL0.jl:20 [inlined]`

2. Does oneArray create USM memory if system is USM capable? What is the best way to know if created memory is USM memory or not? I was trying to find some property attached to memory pointer to decide the same but could not findout anything. Asking this as in case of USM memory access it is applications responsibility to make required sync but in case of buffer memory it is sync by HW/ lower stack.

**Comment by maleadt** [comment]
1. Julia objects are garbage collected, the issue is that the GPU's memory pressure isn't known by the CPU-based GC. The solution is that we force the GC to run when we hit a GPU OOM, but that currently isn't implemented here. You can use `oneAPI.unsafe_free!` to manually early-free an array.
2. No, because AFAIK USM still has a performance overhead. The buffer type (defaulting to DeviceBuffer) indicates whether this is an USM buffer or not.

**Comment by Sarbojit2019** [comment]
@maleadt,
1. Thank! I will try to use `oneAPI.unsafe_free!` in the test to see if MOO issue is resolved.
2. For me almost all oneMKL APIs are using USM version of the API hence the query. I will use buffer type to determine USM buffer.

**Comment by maleadt** [comment]
> For me almost all oneMKL APIs are using USM version of the API hence the query. I will use buffer type to determine USM buffer.

Sorry, I think I'm confused again (all this means different things across GPU back-ends): we **are** already using USM, just not shared buffers, but device ones (i.e. we're calling `zeMemAllocDevice`).

**Comment by maleadt** [comment]
Also, https://github.com/JuliaGPU/oneAPI.jl/pull/244 should fix your OOM problem without requiring `unsafe_free!`.

**Comment by pengtu** [comment]
> > For me almost all oneMKL APIs are using USM version of the API hence the query. I will use buffer type to determine USM buffer.
> 
> Sorry, I think I'm confused again (all this means different things across GPU back-ends): I think we **are** already using USM, just not shared buffers, but device ones (i.e. we're calling `zeMemAllocDevice`).

That is correct.  The sycl::buffer is a SYCL only concept,  where SYCL runtime manages the copying of the 'buffer' between host and device sycl::accessor.  Julia oneAPI uses zeMemAllocDevice for oneArray and manages the copying between Array and oneArray.

oneAPI.jl's MKL calls use the sycl::buffer interface and pass a Level 0, ZePtr to the oneMKL library. oneMKL doesn't allocate/release any the of the Level Zero objects.

**Comment by pengtu** [comment]
The Array(A) == Array(B) test also passes if we add a 'wait' in the C wrapper.
https://github.com/JuliaGPU/oneAPI.jl/blob/master/test/onemkl.jl#L15

Again, there should already been a GPU synchronization in the Array(A), Array(B) operations, unless the GPU synchronization occurs before the MKL copy task has been submitted, or Julia compiler performed a transformation ignoring the dependency of Array(B) on the oneMKL.copy! operation.

**Comment by pengtu** [comment]
#241

**Comment by Sarbojit2019** [comment]
@pengtu, SYCL_PI_LEVEL_ZERO_BATCH_SIZE=1 did help test to pass. I could complete 200 iteration without any issue (earlier failure was seen within 50 iteration).

I think issue is seen because we (julia runtime) not following one path for task submission and synchronization. Looks like submission goes via Sycl path (hence SYCL can buffer commands) and for Synchronization direct L0 API is called because of which few commands are getting missed in failure case.
Ideal fix would be to go via one path which is sycl path for submission as well as synchronization, then we should not see the problem.

@maleadt 
I don't think setting one batch is right way to fix the problem as it will have performance impact. If we still want to go ahead with one command at a time then I feel immediate command list is better approach than setting environment variable every time.

**Comment by maleadt** [comment]
> Ideal fix would be to go via one path which is sycl path for submission as well as synchronization, then we should not see the problem.

SYCL being a C++ DSL / not having a proper C API / ..., that's not really an option. Shouldn't there be a way to use libraries like oneMKL (which presumably aren't meant to be SYCL-only) with oneL0 applications?

**Comment by Sarbojit2019** [comment]
> > Ideal fix would be to go via one path which is sycl path for submission as well as synchronization, then we should not see the problem.
> 
> SYCL being a C++ DSL / not having a proper C API / ..., that's not really an option. Shouldn't there be a way to use libraries like oneMKL (which presumably aren't meant to be SYCL-only) with oneL0 applications?

Suggestion here is to synchronize on last sycl::event of the queue (in this case sycl::global_queue). Currently julia runtime(JR) calls zeCommandQueueSynchronize for queue synchronization which is direct L0 api for synchronization. Rather JR should call global_queue::last_event.wait().
All oneMKL calls return the event associated to primitives hence it will not be a difficult task for JR to maintain the last event submitted to the queue and use it while synchronization is needed. I think at present JR don't maintain last_event submitted to the queue but that is easy and cleaner approach.

**Comment by maleadt** [comment]
Tracking the last event isn't sufficient, because we have a different global queue per task, so at the very least this should be a task-local property. Still, this isn't a very lightweight solution, effectively requiring a task-local write on almost every oneMKL API call. Instead, isn't it possible to flush the SYCL batch queue (i.e., when synchronizing in Julia) so that oneL0 synchronization just works as intended?

Also note that the Julia runtime is something different and unrelated to what oneAPI.jl is doing here.

**Comment by Sarbojit2019** [comment]
PR raised #247
