### ISSUE TITLE
oneMKL tests are failing. 

### ISSUE THREAD

**Issue by kballeda** [JuliaGPU/oneAPI.jl#271]
Following are the snapshots of level-1,2,3 tests that are failing under tests/onemkl.jl after following commit - https://github.com/JuliaGPU/oneAPI.jl/commit/63fa2c4d6324ea2881c36f5e972f68bca31ae478 in master. @maleadt please let me know if there is a change in the way we test them. I am investigating further at my end as well.

Level-1: 

![level1_failures](https://user-images.githubusercontent.com/114738197/216586976-186d14d7-e21d-4c13-9bae-2d13de617784.png)

Level-2:

![level2_failures](https://user-images.githubusercontent.com/114738197/216587035-c9b61fbd-c27b-4a50-bc26-909d4d44e77f.png)

Level-3:

![level3_failures](https://user-images.githubusercontent.com/114738197/216587080-5a14c1f1-21da-4b18-b751-96971cdab260.png)

**Comment by maleadt** [comment]
Can you post the actual errors? Tests don't fail here or on CI, and as you can see in the diff https://github.com/JuliaGPU/oneAPI.jl/commit/63fa2c4d6324ea2881c36f5e972f68bca31ae478 nothing changed in the wrappers for e.g. `scal`.

**Comment by kballeda** [comment]
I find test cases failed with results mismatch. 
Please find the logs here, 
[level1_error_log.txt](https://github.com/JuliaGPU/oneAPI.jl/files/10580899/level1_error_log.txt)
[level2_error_log.txt](https://github.com/JuliaGPU/oneAPI.jl/files/10580900/level2_error_log.txt)
[level3_error_log.txt](https://github.com/JuliaGPU/oneAPI.jl/files/10580902/level3_error_log.txt)

Following is the fix for level-1 errors,
![image](https://user-images.githubusercontent.com/114738197/216659700-c3d16304-7790-4d76-bd4e-44dec09ccad4.png)

Level-1 Pass:

![image](https://user-images.githubusercontent.com/114738197/216660019-3d04c012-aff1-4abb-a9df-739a520ca614.png)

**Comment by maleadt** [comment]
Ah, right, this happens because we aren't running CI with Float64 (see https://github.com/JuliaGPU/oneAPI.jl/pull/261; this may also be interesting for you to look at).

**Comment by kballeda** [comment]
> Ah, right, this happens because we aren't running CI with Float64 (see #261; this may also be interesting for you to look at).

Thanks a lot for providing a fix.
