### ISSUE TITLE
liboneapi_support: double pointer support required

### ISSUE THREAD

**Issue by kballeda** [JuliaGPU/oneAPI.jl#286]
@maleadt  liboneapi_support library automation needs enhancement to support case explained below.

If prototype of a function in onemkl.h is following,

`void onemklSgemmBatched(syclQueue_t device_queue, onemklTranspose transa, 
                        onemklTranspose transb, int64_t m,
                        int64_t n, int64_t k, float alpha,
                        const float **a, int64_t lda, const float **b,
                        int64_t ldb, float beta, float **c,
                        int64_t ldc, int64_t group_count);`
                        
 When I try to generate liboneapi_support.jl using wrap.jl I get following output, 
 
 `function onemklSgemmBatched(device_queue, transa, transb, m, n, k, alpha, a, lda, b, ldb,
                            beta, c, ldc, group_count)
    @ccall liboneapi_support.onemklSgemmBatched(device_queue::syclQueue_t,
                                                transa::onemklTranspose,
                                                transb::onemklTranspose, m::Int64, n::Int64,
                                                k::Int64, alpha::Cfloat,
                                                a::Ptr{Ptr{Cfloat}}, lda::Int64,
                                                b::Ptr{Ptr{Cfloat}}, ldb::Int64,
                                                beta::Cfloat, c::Ptr{Ptr{Cfloat}},
                                                ldc::Int64, group_count::Int64)::Cvoid`

Here **`a::Ptr{Ptr{Cfloat}}`** is generated where ideally I need **`ZePtr{Ptr{Cfloat}}`** .

**Comment by maleadt** [comment]
You add overrides to the `ze.toml` file for that, e.g., https://github.com/JuliaGPU/oneAPI.jl/blob/da18d5bc4e8f48839c73845e28946d943a7207c3/res/ze.toml#L51-L52

**Comment by kballeda** [comment]
@maleadt  Thanks for your response. I am new to .toml flow and this automation. Can you please guide on generating `ZePtr{Ptr{Cfloat}}` ? I found that in example above 5 refers to argument location and it is of void **pptr in zeMemOpenIpcHandle.

**Comment by kballeda** [comment]
@maleadt  : Updating support.toml file resolved the issue. Thank you.

**Comment by maleadt** [comment]
Sorry for the delay, great you got it sorted out.

**Comment by kballeda** [comment]
> Sorry for the delay, great you got it sorted out.

Not a problem, @pengtu  and I had a discussion and found the correct file to update.
