### ISSUE TITLE
New version of oneAPI_Support_jll?

### ISSUE THREAD

**Issue by amontoison** [JuliaGPU/oneAPI.jl#298]
I use Buildkite with `oneAPI.jl` to test the support of Intel GPUs in my package Krylov.jl and I have some [errors](https://buildkite.com/julialang/krylov-dot-jl/builds/487#018711e1-cbd9-480f-9fad-cf4c134bbc38/113-211) with the functions that I added with this [PR](https://github.com/JuliaGPU/oneAPI.jl/pull/279).
We probably need to regenerate `oneAPI_Support_jll` to add the new symbols.

**Comment by maleadt** [comment]
OK, I'll build a new version.

FYI, you can also do this yourself, by creating a PR on Yggdrasil. Happy to do it, though.

**Comment by amontoison** [comment]
Thanks @maleadt! I will open a PR myself next time. I know what should be recompiled on Yggdrasil now.
