### ISSUE TITLE
Level Zero loader picks system libze_intel_gpu

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/oneAPI.jl#315]
```
julia> Libdl.dlpath(Libdl.dlopen("libze_intel_gpu"))
"/usr/lib/libze_intel_gpu.so"

julia> oneAPI.oneL0.NEO_jll.libze_intel_gpu
"/home/tim/Julia/depot/artifacts/8ec2588dc6394e29e9798f510445a729bec709a1/lib/libze_intel_gpu.so.1"
```

**Comment by maleadt** [comment]
Oh, maybe this isn't bad, as our JLLs provide `libze_intel_gpu.so.1`. I wonder if there's an env var to check which back-end that the Level Zero loader chooses. cc @pengtu

**Comment by pengtu** [comment]
I think you are correct.  There is also an env variable for alternative driver to load:
https://github.com/oneapi-src/level-zero/blob/f9de28829858ca89d76f13311f8fd53453dde562/source/loader/linux/driver_discovery_lin.cpp#L28

**Comment by maleadt** [comment]
> our JLLs provide `libze_intel_gpu.so.1`

https://github.com/JuliaBinaryWrappers/NEO_jll.jl/blob/6f414ac420e0649abd8e11cf02f2c8b0756e288b/src/wrappers/x86_64-linux-gnu-cxx03-debug%2Btrue.jl#L19C31-L23

As we don't do anything special for this on the Yggdrasil side, I've added a small test to ensure this doesn't regress: https://github.com/JuliaGPU/oneAPI.jl/commit/e20e1700c57540c504506cebfe8a7397828a4a7a (I could imagine a BB postprocess pass adding symlinks from version libraries to unversioned ones, and loading that one instead, which would be bad here).
