### ISSUE TITLE
Kernel compilation fail when using `sqrt` and similar function

### ISSUE THREAD

**Issue by cdsousa** [JuliaGPU/oneAPI.jl#35]
MWE:
```julia
using oneAPI
function fff(a, s)
    a[1] = sqrt(s)
    # a[1] = oneAPI.sqrt(s)  # this one works
    return nothing
end
@oneapi items=1  fff(oneArray([0.0f0]), 1.23f0)
```
gives
```InvalidFunctionCall: Unexpected llvm intrinsic: llvm.sqrt.f32 [Src: ../lib/SPIRV/SPIRVWriter.cpp:1491  ]```

Also fails with `abs`, for example.

(feel free to change the issue title)

**Comment by maleadt** [comment]
Yeah, this is similar to CUDA, where you need to use `CUDA.sqrt`. So I'm closing this as a dup of https://github.com/JuliaGPU/CUDA.jl/issues/73.
