### ISSUE TITLE
precompile error for SPIRV_LLVM_Translator_jll

### ISSUE THREAD

**Issue by bd4** [JuliaGPU/oneAPI.jl#41]
I get an error precompiling oneAPI:
```
(oneapi) pkg> precompile
Precompiling project...
[ Info: Precompiling oneAPI [8f75cd03-7ff8-4ecb-9b8f-daf728133b1b]
ERROR: LoadError: InitError: could not load library "/home/bda/.julia/artifacts/6b3e339c94c460d95f35b5c6cc186f3d829b31de/lib/libLLVMSPIRVLib.so"
libLLVM-9jl.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] dlopen(::String, ::UInt32) at /build/julia/src/julia-1.5.3/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
 [2] macro expansion at /home/bda/.julia/packages/JLLWrappers/KuIwt/src/products/library_generators.jl:61 [inlined]
 [3] __init__() at /home/bda/.julia/packages/SPIRV_LLVM_Translator_jll/E4bij/src/wrappers/x86_64-linux-gnu-cxx11.jl:9
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:331 [inlined]
during initialization of module SPIRV_LLVM_Translator_jll
in expression starting at /home/bda/.julia/packages/oneAPI/UcBkX/src/oneAPI.jl:12
```

I see this error on Debian testing (with default clang 10) and on Arch linux (with default clang 11). Note that `libLLVMSPIRVLib.so` is a symlink to `libLLVMSPIRVLib.so.9jl` which does exist, but `libLLVM-9jl.so` does not.

**Comment by maleadt** [comment]
`libLLVM-9jl.so` is provided by your Julia installation. As per https://github.com/JuliaRegistries/General/blob/ae0472f93585835738d1623820ce088726d20f0e/S/SPIRV_LLVM_Translator_jll/Compat.toml#L14-L15 the version of SPIRV_LLVM_Translator_jll that requires this library should only be installable on Julia 1.5, which provides this specific version. Could you give some details on your set-up? System-provided LLVM builds of Julia are currently not supported, but should be at some point in the future.

**Comment by bd4** [comment]
On Arch Linux I have Julia 1.5.3 installed via the native package manager, and on Debian testing same version installed via apt. Neither packages include any .so files. On both systems, the julia executable is linked to system libLLVM-10.so.

The binary for 1.5.3, x86_64 available from julialang.org does contain libLLVM-9jl.so, and copying that to `.julia/artifacts/6b3e339c94c460d95f35b5c6cc186f3d829b31de/lib/` results in another error that multiple LLVM libraries are enabled. I'll try setting up an environment with the downloaded binary build to make it work, until system provided LLVM is supported. Thanks for your work on this!

**Comment by maleadt** [comment]
> On Arch Linux I have Julia 1.5.3 installed via the native package manager, and on Debian testing same version installed via apt. Neither packages include any .so files. On both systems, the julia executable is linked to system libLLVM-10.so.

Distribution-provided packages are unsupported, sadly. Even when we'll support loading the SPIRV translator against a system-provided LLVM, the GPU compiler might not work since we carry several packages. So I'd strongly advise to use Julia's official binaries.l
