### ISSUE TITLE
Infinite partial_mapreduce_device recursion

### ISSUE THREAD

**Issue by michel2323** [JuliaGPU/oneAPI.jl#426]
When running
```
julia --project -e 'using oneAPI; sum(oneAPI.zeros(30000)) ; sum(oneAPI.zeros(2182))'
```
the reduction for the 30,000 case runs fine. However, for the 2182 it crashes with an InvalidIRError.

I then added some debug output into https://github.com/JuliaGPU/oneAPI.jl/blob/7973a8980f30bd1b543d1df8a95d099cfbb78c71/src/mapreduce.jl#L164-L178 .

It seems the recursion for the 2182 is infinite. I would suspect it to be shallower than for the 30000 case. I attached a log with some debug output. Maybe there is something obvious to you @maleadt .

[out.log](https://github.com/JuliaGPU/oneAPI.jl/files/15028444/out.log)

**Comment by maleadt** [comment]
Looks like Level Zero's `zeKernelSuggestGroupSize` doesn't like prime-sized global sizes:

```
suggest_groupsize(kernel.fun, 512) = oneAPI.oneL0.ZeDim3(512, 1, 1)
suggest_groupsize(kernel.fun, 513) = oneAPI.oneL0.ZeDim3(27, 1, 1)
suggest_groupsize(kernel.fun, 521) = oneAPI.oneL0.ZeDim3(1, 1, 1)
```

These look like really bad launch configurations...
