### ISSUE TITLE
Double type is not supported on this platform

### ISSUE THREAD

**Issue by hellmrf** [JuliaGPU/oneAPI.jl#50]
I'm trying oneAPI in Julia 1.6.0 running on a Linux 5.4.0 machine with an Intel Core i7-1065G7 (with iGPU Intel Iris Plus G7). As suggested by README, I ran the "smoke-test" and everything worked well (got `ZeDevice(GPU, vendor 0x8086, device 0x8a52): Intel(R) Graphics [0x8a52]`).

However, when I run `] test oneAPI` I get the same error multiple times:

```
┌ Error: Module compilation failed:
│ 
│ error: double type is not supported on this platform
│ error: backend compiler failed build.
└ @ oneAPI.oneL0 ~/.julia/packages/oneAPI/yKhRw/lib/level-zero/module.jl:49
```

The tests that fail with this error are the following:
- execution
- level-zero
- device/intrinsics
- gpuarrays/math
- gpuarrays/indexing scalar
- gpuarrays/value constructors
- gpuarrays/indexing multidimensional
- gpuarrays/iterator constructors
- gpuarrays/linear algebra
- gpuarrays/random
- gpuarrays/base
- gpuarrays/mapreduce essentials
- gpuarrays/broadcasting

and probably more that I didn't wait to see.

This simple code also throw the same error:
```julia
julia> a = oneArray(rand(2,2))
2×2 oneArray{Float64, 2}:
 0.28361    0.367083
 0.0142196  0.783932

julia> a .+ 1
┌ Error: Module compilation failed:
│ 
│ error: double type is not supported on this platform
│ error: backend compiler failed build.
└ @ oneAPI.oneL0 ~/.julia/packages/oneAPI/yKhRw/lib/level-zero/module.jl:49
```

**Comment by maleadt** [comment]
Interesting, I didn't know there were platforms like that. Maybe we should adapt the tests to only use Float32.



> This simple code also throw the same error:

That's expected. If your platform doesn't support doubles, and you create an array of double-precision Float64's... Try `rand(Float32, 2, 2)` instead.

**Comment by hellmrf** [comment]
It's weird because I'm using recent hardware (that does support double). Julia's built-in Float64 works as expected, but this problem occurs with `oneArray`.

```julia
julia> d = rand(Float64, 2, 2)
2×2 Matrix{Float64}:
 0.985023  0.804608
 0.783873  0.803954

julia> d .+ 1
2×2 Matrix{Float64}:
 1.98502  1.80461
 1.78387  1.80395

julia> d1 = oneArray(rand(2,2))
2×2 oneArray{Float64, 2}:
 0.808706  0.865167
 0.53884   0.540602

julia> d1 .+ 1
┌ Error: Module compilation failed:
│ 
│ error: double type is not supported on this platform
│ error: backend compiler failed build.
└ @ oneAPI.oneL0 ~/.julia/packages/oneAPI/yKhRw/lib/level-zero/module.jl:49
ERROR: ZeError: error occurred when building module, see build log for details (code 1879048196, ZE_RESULT_ERROR_MODULE_BUILD_FAILURE)
Stacktrace:
…
```

`oneArray` only works with Float32 (`oneArray(rand(Float32, 2, 2))` is fine).

---

Here my `versioninfo()`:
```plain
Julia Version 1.6.0-DEV.1699
Commit 8a5ac94e96* (2020-12-08 03:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, icelake-client)
```

**Comment by maleadt** [comment]
> It's weird because I'm using recent hardware (that does support double). Julia's built-in Float64 works as expected, but this problem occurs with `oneArray`.

Those aren't comparable/related, and this is a limitation of the oneAPI compiler for your hardware.

**Comment by SoulEater45** [comment]
I have had a similar issue where I got `error: Double type is not supported on this platform`. By adding the following variables to the environment, I was able to solve the issue:
```shell
OverrideDefaultFP64Settings=1 
IGC_EnableDPEmulation=1 
```
I got this solution from the [intel community forum](https://community.intel.com/t5/Intel-DevCloud/Iris-Xe-MAX-node-is-missing-double-precision-support/m-p/1247876), and it worked on my `Intel TigerLake-LP GT2 [Iris Xe Graphics]` GPU.

**Comment by maleadt** [comment]
That's a great tip, thanks! We can even detect this:

```
❯ jl
julia> using oneAPI

julia> oneL0.module_properties(device()).fp64flags
0x00000000
```

```
❯ OverrideDefaultFP64Settings=1 IGC_EnableDPEmulation=1 jl

julia> using oneAPI

julia> oneL0.module_properties(device()).fp64flags
0x0000007f

julia> float64_supported = oneL0.module_properties(device()).fp64flags & oneL0.ZE_DEVICE_MODULE_FLAG_FP64 == oneL0.ZE_DEVICE_MODULE_FLAG_FP64
true
```
