### ISSUE TITLE
cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by felkr** [JuliaGPU/oneAPI.jl#72]
I am getting an error when I try to import oneAPI
```
julia> using oneAPI
[ Info: Precompiling oneAPI [8f75cd03-7ff8-4ecb-9b8f-daf728133b1b]
ERROR: LoadError: InitError: could not load library "/home/[redacted]/.julia/artifacts/769012422c18bf09c53376e964a7fb286d1799c8/lib/libLLVMSPIRVLib.so"
libLLVM-11jl.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] dlopen(s::String, flags::UInt32)
   @ Base.Libc.Libdl ./libdl.jl:114
 [2] macro expansion
   @ ~/.julia/packages/JLLWrappers/bkwIo/src/products/library_generators.jl:54 [inlined]
 [3] __init__()
   @ SPIRV_LLVM_Translator_jll ~/.julia/packages/SPIRV_LLVM_Translator_jll/Zez7T/src/wrappers/x86_64-linux-gnu-cxx11.jl:9
 [4] top-level scope (repeats 2 times)
   @ none:1
during initialization of module SPIRV_LLVM_Translator_jll
in expression starting at /home/[redacted]/.julia/packages/oneAPI/zydrg/src/oneAPI.jl:1
ERROR: Failed to precompile oneAPI [8f75cd03-7ff8-4ecb-9b8f-daf728133b1b] to /home/felix/.julia/compiled/v1.6/oneAPI/jl_aWfrhe.
Stacktrace:
 [1] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY)
   @ Base ./loading.jl:1360

```

**Comment by maleadt** [comment]
Please provide some essential details: which version of Julia, where did you get it from, which version of the package, etc.

**Comment by felkr** [comment]
OS: Artix Linux (essentially Arch with OpenRC instead of SystemD)
Julia Version: julia version 1.6.1 (installed [via pacman](https://archlinux.org/packages/community/x86_64/julia/))
Package Version: oneAPI v0.1.2 (determined via `pkg> status oneAPI`)

**Comment by maleadt** [comment]
>  Julia Version: julia version 1.6.1 (installed [via pacman](https://archlinux.org/packages/community/x86_64/julia/))

Yeah, I figured as much... Linux distro-provided versions of Julia are sadly not supported. The use of `USE_SYSTEM_LLVM` makes it impossible to; we vendor LLVM for a reason, including several patches and fixes that matter, especially for GPU back-ends.

I suggest you use the `julia-bin` package, also from the AUR. It uses the official Julia binaries from julialang.org. That should resolve your issue.
