### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mobius-eng** [JuliaGPU/oneAPI.jl#92]
Trying

```julia
using oneAPI
```

Get the error:

```
ERROR: InitError: UndefVarError: libze_loader not defined
Stacktrace:
 [1] unsafe_zeInit
   @ C:\Users\alexeyc\.julia\packages\oneAPI\bEvNc\lib\level-zero\libze.jl:895 [inlined]
 [2] __init__()
   @ oneAPI.oneL0 C:\Users\alexeyc\.julia\packages\oneAPI\bEvNc\lib\level-zero\oneL0.jl:93
 [3] _include_from_serialized(path::String, depmods::Vector{Any})
   @ Base .\loading.jl:696
 [4] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
   @ Base .\loading.jl:782
 [5] _require(pkg::Base.PkgId)
   @ Base .\loading.jl:1020
 [6] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:936
 [7] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:923
during initialization of module oneL0
```

Windows 10, Julia 1.6.2 (2021-07-14)

**Comment by mobius-eng** [comment]
I think the reason for the error might be that my processor is not supported for "Level Zero" (based on https://github.com/intel/compute-runtime)

**Comment by maleadt** [comment]
oneAPI.jl currently only supports Linux, sorry.

**Comment by mobius-eng** [comment]
Ah, I see...

**Comment by maleadt** [comment]
Apparently WSL2 just works. Native support isn't going to be happening soon, as the driver stack is entirely different.

**Comment by RoyiAvital** [comment]
Will Windows be supported?

**Comment by maleadt** [comment]
If somebody works on that. I currently don't have such plans, but if you're a Windows user you could take a stab (e.g., figuring out if you we can compile and/or redistribute the driver, or whether and how it needs to be discovered).

**Comment by RoyiAvital** [comment]
I guess I'm on the other phase of the chicken egg circle :-).
I'd buy this card if I knew it worked on Windows.

**Comment by pengtu** [comment]
As Tim said, WSL2 works just fine.

**Comment by RoyiAvital** [comment]
Well, I use Windows because I like working in Windows and not in Linux / GNU.
Don't want to make it Windows vs. Linux, just wanted to share there is a demand and hopefully we'll see support.

**Comment by el-oso** [comment]
how to get started on this?

**Comment by maleadt** [comment]
I'd look for a oneAPI Windows example and install it with the Intel toolchain, and inspect the generated code / resulting binary. If it uses Level Zero API calls, it should link against or dynamically open a library that provides that API; we should also discover that library in oneAPI.jl and use it instead of oneL0_jll. If it uses a different API, Windows support will be out of scope for this package.

**Comment by maleadt** [comment]
Looks like `ze_loader.dll` _is_ available on Windows, and is installed on System32, so this may be easier than I thought.

**Comment by maleadt** [comment]
I recently managed to get oneAPI.jl working on my local WSL installation (i.e., not triggering https://github.com/intel/compute-runtime/issues/663 anymore), and it seems like the package is generally working just fine, with all tests passing :tada: 

Native support, where we directly interface with the driver without requiring WSL, would still be nice to have though. @el-oso is WSL a viable option for you for the time being? All it requires is `wsl --install`, setting up Julia inside of that VM (e.g. by installing `juliaup`), and using Julia/oneAPI.jl from there.

**Comment by maleadt** [comment]
> Looks like `ze_loader.dll` _is_ available on Windows, and is installed on System32, so this may be easier than I thought.

This seems to work reasonably, so native Windows support should be possible too. That won't include support for oneMKL etc though, so WSL will be a better option in the short term.



> I will test it tomorrow on my work laptop and let you know if this would be a viable option for me, at least for now.

If you run into issues, also try the master branch of oneAPI.jl.

**Comment by maleadt** [comment]
Let's close this, as we have Windows support through WSL now. I'll open a separate issue to track native windows support.
